version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: changemerightaway
    ports:
      - 5432:5432

  inventory:
    build: .
    ports:
      - 8000:8000
      - 9000:9000
    environment:
      INVENTORY_STORAGE_URI: postgres://postgres:changemerightaway@db/postgres?sslmode=disable
      INVENTORY_HTTP_AUTH_ENABLED: true
    depends_on:
      - "db"
