version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: changemerightaway
    ports:
      - 5432:5432

  inventory:
    build: .
    ports:
      - 8000:8000
    environment:
      INVENTORY_DB_URI: postgres://postgres:changemerightaway@db/postgres?sslmode=disable
    volumes:
      - ./config:/data/config
    depends_on:
      - "db"