// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type VehicleServiceHTTPServer interface {
	CreateVehicle(context.Context, *CreateVehicleRequest) (*CreateVehicleReply, error)
	DeleteVehicle(context.Context, *DeleteVehicleRequest) (*DeleteVehicleReply, error)
	GetVehicle(context.Context, *GetVehicleRequest) (*GetVehicleReply, error)
	ListVehicle(context.Context, *ListVehicleRequest) (*ListVehicleReply, error)
	UpdateVehicle(context.Context, *UpdateVehicleRequest) (*UpdateVehicleReply, error)
}

func RegisterVehicleServiceHTTPServer(s *http.Server, srv VehicleServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/vehicles", _VehicleService_CreateVehicle0_HTTP_Handler(srv))
	r.PUT("/vehicles", _VehicleService_UpdateVehicle0_HTTP_Handler(srv))
	r.DELETE("/vehicles/{id}", _VehicleService_DeleteVehicle0_HTTP_Handler(srv))
	r.DELETE("/vehicles/{id}", _VehicleService_GetVehicle0_HTTP_Handler(srv))
	r.GET("/vehicles/", _VehicleService_ListVehicle0_HTTP_Handler(srv))
}

func _VehicleService_CreateVehicle0_HTTP_Handler(srv VehicleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVehicleRequest
		if err := ctx.Bind(&in.Vehicle); err != nil {
			return err
		}
		http.SetOperation(ctx, "/vehicles.service.v1.VehicleService/CreateVehicle")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVehicle(ctx, req.(*CreateVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateVehicleReply)
		return ctx.Result(200, reply)
	}
}

func _VehicleService_UpdateVehicle0_HTTP_Handler(srv VehicleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateVehicleRequest
		if err := ctx.Bind(&in.Vehicle); err != nil {
			return err
		}
		http.SetOperation(ctx, "/vehicles.service.v1.VehicleService/UpdateVehicle")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateVehicle(ctx, req.(*UpdateVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateVehicleReply)
		return ctx.Result(200, reply)
	}
}

func _VehicleService_DeleteVehicle0_HTTP_Handler(srv VehicleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteVehicleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/vehicles.service.v1.VehicleService/DeleteVehicle")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteVehicle(ctx, req.(*DeleteVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteVehicleReply)
		return ctx.Result(200, reply)
	}
}

func _VehicleService_GetVehicle0_HTTP_Handler(srv VehicleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVehicleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/vehicles.service.v1.VehicleService/GetVehicle")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVehicle(ctx, req.(*GetVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetVehicleReply)
		return ctx.Result(200, reply)
	}
}

func _VehicleService_ListVehicle0_HTTP_Handler(srv VehicleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVehicleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/vehicles.service.v1.VehicleService/ListVehicle")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVehicle(ctx, req.(*ListVehicleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVehicleReply)
		return ctx.Result(200, reply)
	}
}

type VehicleServiceHTTPClient interface {
	CreateVehicle(ctx context.Context, req *CreateVehicleRequest, opts ...http.CallOption) (rsp *CreateVehicleReply, err error)
	DeleteVehicle(ctx context.Context, req *DeleteVehicleRequest, opts ...http.CallOption) (rsp *DeleteVehicleReply, err error)
	GetVehicle(ctx context.Context, req *GetVehicleRequest, opts ...http.CallOption) (rsp *GetVehicleReply, err error)
	ListVehicle(ctx context.Context, req *ListVehicleRequest, opts ...http.CallOption) (rsp *ListVehicleReply, err error)
	UpdateVehicle(ctx context.Context, req *UpdateVehicleRequest, opts ...http.CallOption) (rsp *UpdateVehicleReply, err error)
}

type VehicleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewVehicleServiceHTTPClient(client *http.Client) VehicleServiceHTTPClient {
	return &VehicleServiceHTTPClientImpl{client}
}

func (c *VehicleServiceHTTPClientImpl) CreateVehicle(ctx context.Context, in *CreateVehicleRequest, opts ...http.CallOption) (*CreateVehicleReply, error) {
	var out CreateVehicleReply
	pattern := "/vehicles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/vehicles.service.v1.VehicleService/CreateVehicle"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Vehicle, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *VehicleServiceHTTPClientImpl) DeleteVehicle(ctx context.Context, in *DeleteVehicleRequest, opts ...http.CallOption) (*DeleteVehicleReply, error) {
	var out DeleteVehicleReply
	pattern := "/vehicles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/vehicles.service.v1.VehicleService/DeleteVehicle"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *VehicleServiceHTTPClientImpl) GetVehicle(ctx context.Context, in *GetVehicleRequest, opts ...http.CallOption) (*GetVehicleReply, error) {
	var out GetVehicleReply
	pattern := "/vehicles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/vehicles.service.v1.VehicleService/GetVehicle"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *VehicleServiceHTTPClientImpl) ListVehicle(ctx context.Context, in *ListVehicleRequest, opts ...http.CallOption) (*ListVehicleReply, error) {
	var out ListVehicleReply
	pattern := "/vehicles/"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/vehicles.service.v1.VehicleService/ListVehicle"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *VehicleServiceHTTPClientImpl) UpdateVehicle(ctx context.Context, in *UpdateVehicleRequest, opts ...http.CallOption) (*UpdateVehicleReply, error) {
	var out UpdateVehicleReply
	pattern := "/vehicles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/vehicles.service.v1.VehicleService/UpdateVehicle"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in.Vehicle, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
