// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	_vehicle "github.com/open-farms/inventory/ent/vehicle"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp(in *jlexer.Lexer, out *VehicleUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "make":
			if in.IsNull() {
				in.Skip()
				out.Make = nil
			} else {
				if out.Make == nil {
					out.Make = new(string)
				}
				*out.Make = string(in.String())
			}
		case "model":
			if in.IsNull() {
				in.Skip()
				out.Model = nil
			} else {
				if out.Model == nil {
					out.Model = new(string)
				}
				*out.Model = string(in.String())
			}
		case "miles":
			if in.IsNull() {
				in.Skip()
				out.Miles = nil
			} else {
				if out.Miles == nil {
					out.Miles = new(int64)
				}
				*out.Miles = int64(in.Int64())
			}
		case "mpg":
			if in.IsNull() {
				in.Skip()
				out.Mpg = nil
			} else {
				if out.Mpg == nil {
					out.Mpg = new(int64)
				}
				*out.Mpg = int64(in.Int64())
			}
		case "owner":
			if in.IsNull() {
				in.Skip()
				out.Owner = nil
			} else {
				if out.Owner == nil {
					out.Owner = new(string)
				}
				*out.Owner = string(in.String())
			}
		case "year":
			if in.IsNull() {
				in.Skip()
				out.Year = nil
			} else {
				if out.Year == nil {
					out.Year = new(string)
				}
				*out.Year = string(in.String())
			}
		case "active":
			if in.IsNull() {
				in.Skip()
				out.Active = nil
			} else {
				if out.Active == nil {
					out.Active = new(bool)
				}
				*out.Active = bool(in.Bool())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				if out.Tags == nil {
					out.Tags = new([]string)
				}
				if in.IsNull() {
					in.Skip()
					*out.Tags = nil
				} else {
					in.Delim('[')
					if *out.Tags == nil {
						if !in.IsDelim(']') {
							*out.Tags = make([]string, 0, 4)
						} else {
							*out.Tags = []string{}
						}
					} else {
						*out.Tags = (*out.Tags)[:0]
					}
					for !in.IsDelim(']') {
						var v1 string
						v1 = string(in.String())
						*out.Tags = append(*out.Tags, v1)
						in.WantComma()
					}
					in.Delim(']')
				}
			}
		case "condition":
			if in.IsNull() {
				in.Skip()
				out.Condition = nil
			} else {
				if out.Condition == nil {
					out.Condition = new(_vehicle.Condition)
				}
				*out.Condition = _vehicle.Condition(in.String())
			}
		case "update_time":
			if in.IsNull() {
				in.Skip()
				out.UpdateTime = nil
			} else {
				if out.UpdateTime == nil {
					out.UpdateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdateTime).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp(out *jwriter.Writer, in VehicleUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"make\":"
		out.RawString(prefix[1:])
		if in.Make == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Make))
		}
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		if in.Model == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Model))
		}
	}
	{
		const prefix string = ",\"miles\":"
		out.RawString(prefix)
		if in.Miles == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Miles))
		}
	}
	{
		const prefix string = ",\"mpg\":"
		out.RawString(prefix)
		if in.Mpg == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Mpg))
		}
	}
	{
		const prefix string = ",\"owner\":"
		out.RawString(prefix)
		if in.Owner == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Owner))
		}
	}
	{
		const prefix string = ",\"year\":"
		out.RawString(prefix)
		if in.Year == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Year))
		}
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		if in.Active == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.Active))
		}
	}
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix)
		if in.Tags == nil {
			out.RawString("null")
		} else {
			if *in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
				out.RawString("null")
			} else {
				out.RawByte('[')
				for v2, v3 := range *in.Tags {
					if v2 > 0 {
						out.RawByte(',')
					}
					out.String(string(v3))
				}
				out.RawByte(']')
			}
		}
	}
	{
		const prefix string = ",\"condition\":"
		out.RawString(prefix)
		if in.Condition == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Condition))
		}
	}
	{
		const prefix string = ",\"update_time\":"
		out.RawString(prefix)
		if in.UpdateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.UpdateTime).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VehicleUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VehicleUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp1(in *jlexer.Lexer, out *VehicleCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "make":
			if in.IsNull() {
				in.Skip()
				out.Make = nil
			} else {
				if out.Make == nil {
					out.Make = new(string)
				}
				*out.Make = string(in.String())
			}
		case "model":
			if in.IsNull() {
				in.Skip()
				out.Model = nil
			} else {
				if out.Model == nil {
					out.Model = new(string)
				}
				*out.Model = string(in.String())
			}
		case "miles":
			if in.IsNull() {
				in.Skip()
				out.Miles = nil
			} else {
				if out.Miles == nil {
					out.Miles = new(int64)
				}
				*out.Miles = int64(in.Int64())
			}
		case "mpg":
			if in.IsNull() {
				in.Skip()
				out.Mpg = nil
			} else {
				if out.Mpg == nil {
					out.Mpg = new(int64)
				}
				*out.Mpg = int64(in.Int64())
			}
		case "owner":
			if in.IsNull() {
				in.Skip()
				out.Owner = nil
			} else {
				if out.Owner == nil {
					out.Owner = new(string)
				}
				*out.Owner = string(in.String())
			}
		case "year":
			if in.IsNull() {
				in.Skip()
				out.Year = nil
			} else {
				if out.Year == nil {
					out.Year = new(string)
				}
				*out.Year = string(in.String())
			}
		case "active":
			if in.IsNull() {
				in.Skip()
				out.Active = nil
			} else {
				if out.Active == nil {
					out.Active = new(bool)
				}
				*out.Active = bool(in.Bool())
			}
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				if out.Tags == nil {
					out.Tags = new([]string)
				}
				if in.IsNull() {
					in.Skip()
					*out.Tags = nil
				} else {
					in.Delim('[')
					if *out.Tags == nil {
						if !in.IsDelim(']') {
							*out.Tags = make([]string, 0, 4)
						} else {
							*out.Tags = []string{}
						}
					} else {
						*out.Tags = (*out.Tags)[:0]
					}
					for !in.IsDelim(']') {
						var v4 string
						v4 = string(in.String())
						*out.Tags = append(*out.Tags, v4)
						in.WantComma()
					}
					in.Delim(']')
				}
			}
		case "condition":
			if in.IsNull() {
				in.Skip()
				out.Condition = nil
			} else {
				if out.Condition == nil {
					out.Condition = new(_vehicle.Condition)
				}
				*out.Condition = _vehicle.Condition(in.String())
			}
		case "create_time":
			if in.IsNull() {
				in.Skip()
				out.CreateTime = nil
			} else {
				if out.CreateTime == nil {
					out.CreateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CreateTime).UnmarshalJSON(data))
				}
			}
		case "update_time":
			if in.IsNull() {
				in.Skip()
				out.UpdateTime = nil
			} else {
				if out.UpdateTime == nil {
					out.UpdateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdateTime).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp1(out *jwriter.Writer, in VehicleCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"make\":"
		out.RawString(prefix[1:])
		if in.Make == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Make))
		}
	}
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix)
		if in.Model == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Model))
		}
	}
	{
		const prefix string = ",\"miles\":"
		out.RawString(prefix)
		if in.Miles == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Miles))
		}
	}
	{
		const prefix string = ",\"mpg\":"
		out.RawString(prefix)
		if in.Mpg == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.Mpg))
		}
	}
	{
		const prefix string = ",\"owner\":"
		out.RawString(prefix)
		if in.Owner == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Owner))
		}
	}
	{
		const prefix string = ",\"year\":"
		out.RawString(prefix)
		if in.Year == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Year))
		}
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		if in.Active == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.Active))
		}
	}
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix)
		if in.Tags == nil {
			out.RawString("null")
		} else {
			if *in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
				out.RawString("null")
			} else {
				out.RawByte('[')
				for v5, v6 := range *in.Tags {
					if v5 > 0 {
						out.RawByte(',')
					}
					out.String(string(v6))
				}
				out.RawByte(']')
			}
		}
	}
	{
		const prefix string = ",\"condition\":"
		out.RawString(prefix)
		if in.Condition == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Condition))
		}
	}
	{
		const prefix string = ",\"create_time\":"
		out.RawString(prefix)
		if in.CreateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.CreateTime).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"update_time\":"
		out.RawString(prefix)
		if in.UpdateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.UpdateTime).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VehicleCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VehicleCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp1(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp2(in *jlexer.Lexer, out *Vehicle2848838632Views) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Vehicle2848838632Views, 0, 8)
			} else {
				*out = Vehicle2848838632Views{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v7 *Vehicle2848838632View
			if in.IsNull() {
				in.Skip()
				v7 = nil
			} else {
				if v7 == nil {
					v7 = new(Vehicle2848838632View)
				}
				(*v7).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v7)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp2(out *jwriter.Writer, in Vehicle2848838632Views) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in {
			if v8 > 0 {
				out.RawByte(',')
			}
			if v9 == nil {
				out.RawString("null")
			} else {
				(*v9).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vehicle2848838632Views) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vehicle2848838632Views) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp2(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp3(in *jlexer.Lexer, out *Vehicle2848838632View) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "make":
			out.Make = string(in.String())
		case "model":
			out.Model = string(in.String())
		case "miles":
			out.Miles = int64(in.Int64())
		case "mpg":
			out.Mpg = int64(in.Int64())
		case "owner":
			out.Owner = string(in.String())
		case "year":
			out.Year = string(in.String())
		case "active":
			out.Active = bool(in.Bool())
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]string, 0, 4)
					} else {
						out.Tags = []string{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					v10 = string(in.String())
					out.Tags = append(out.Tags, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "condition":
			out.Condition = _vehicle.Condition(in.String())
		case "create_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreateTime).UnmarshalJSON(data))
			}
		case "update_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdateTime).UnmarshalJSON(data))
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp3(out *jwriter.Writer, in Vehicle2848838632View) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	if in.Make != "" {
		const prefix string = ",\"make\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Make))
	}
	if in.Model != "" {
		const prefix string = ",\"model\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Model))
	}
	if in.Miles != 0 {
		const prefix string = ",\"miles\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Miles))
	}
	if in.Mpg != 0 {
		const prefix string = ",\"mpg\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Mpg))
	}
	if in.Owner != "" {
		const prefix string = ",\"owner\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Owner))
	}
	if in.Year != "" {
		const prefix string = ",\"year\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Year))
	}
	if in.Active {
		const prefix string = ",\"active\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Active))
	}
	if len(in.Tags) != 0 {
		const prefix string = ",\"tags\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Tags {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	if in.Condition != "" {
		const prefix string = ",\"condition\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Condition))
	}
	if true {
		const prefix string = ",\"create_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.CreateTime).MarshalJSON())
	}
	if true {
		const prefix string = ",\"update_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.UpdateTime).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vehicle2848838632View) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vehicle2848838632View) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp3(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp4(in *jlexer.Lexer, out *ErrResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "status":
			out.Status = string(in.String())
		case "errors":
			if m, ok := out.Errors.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Errors.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Errors = in.Interface()
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp4(out *jwriter.Writer, in ErrResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.Errors != nil {
		const prefix string = ",\"errors\":"
		out.RawString(prefix)
		if m, ok := in.Errors.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Errors.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Errors))
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp4(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp4(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp5(in *jlexer.Lexer, out *EquipmentUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "condition":
			if in.IsNull() {
				in.Skip()
				out.Condition = nil
			} else {
				if out.Condition == nil {
					out.Condition = new(string)
				}
				*out.Condition = string(in.String())
			}
		case "update_time":
			if in.IsNull() {
				in.Skip()
				out.UpdateTime = nil
			} else {
				if out.UpdateTime == nil {
					out.UpdateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdateTime).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp5(out *jwriter.Writer, in EquipmentUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"condition\":"
		out.RawString(prefix)
		if in.Condition == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Condition))
		}
	}
	{
		const prefix string = ",\"update_time\":"
		out.RawString(prefix)
		if in.UpdateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.UpdateTime).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EquipmentUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp5(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EquipmentUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp5(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp6(in *jlexer.Lexer, out *EquipmentCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "condition":
			if in.IsNull() {
				in.Skip()
				out.Condition = nil
			} else {
				if out.Condition == nil {
					out.Condition = new(string)
				}
				*out.Condition = string(in.String())
			}
		case "create_time":
			if in.IsNull() {
				in.Skip()
				out.CreateTime = nil
			} else {
				if out.CreateTime == nil {
					out.CreateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CreateTime).UnmarshalJSON(data))
				}
			}
		case "update_time":
			if in.IsNull() {
				in.Skip()
				out.UpdateTime = nil
			} else {
				if out.UpdateTime == nil {
					out.UpdateTime = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdateTime).UnmarshalJSON(data))
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp6(out *jwriter.Writer, in EquipmentCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"condition\":"
		out.RawString(prefix)
		if in.Condition == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Condition))
		}
	}
	{
		const prefix string = ",\"create_time\":"
		out.RawString(prefix)
		if in.CreateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.CreateTime).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"update_time\":"
		out.RawString(prefix)
		if in.UpdateTime == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.UpdateTime).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EquipmentCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp6(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EquipmentCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp6(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp7(in *jlexer.Lexer, out *Equipment822375389Views) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Equipment822375389Views, 0, 8)
			} else {
				*out = Equipment822375389Views{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v13 *Equipment822375389View
			if in.IsNull() {
				in.Skip()
				v13 = nil
			} else {
				if v13 == nil {
					v13 = new(Equipment822375389View)
				}
				(*v13).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v13)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp7(out *jwriter.Writer, in Equipment822375389Views) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v14, v15 := range in {
			if v14 > 0 {
				out.RawByte(',')
			}
			if v15 == nil {
				out.RawString("null")
			} else {
				(*v15).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Equipment822375389Views) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp7(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Equipment822375389Views) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp7(l, v)
}
func easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp8(in *jlexer.Lexer, out *Equipment822375389View) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "condition":
			out.Condition = string(in.String())
		case "create_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreateTime).UnmarshalJSON(data))
			}
		case "update_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdateTime).UnmarshalJSON(data))
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp8(out *jwriter.Writer, in Equipment822375389View) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Condition != "" {
		const prefix string = ",\"condition\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Condition))
	}
	if true {
		const prefix string = ",\"create_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.CreateTime).MarshalJSON())
	}
	if true {
		const prefix string = ",\"update_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.UpdateTime).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Equipment822375389View) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5a4559bEncodeGithubComOpenFarmsInventoryEntHttp8(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Equipment822375389View) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5a4559bDecodeGithubComOpenFarmsInventoryEntHttp8(l, v)
}
