// Code generated by entc, DO NOT EDIT.

package http

import (
	"net/http"
	"strconv"
	"time"

	"github.com/mailru/easyjson"
	"github.com/open-farms/inventory/ent"
)

// Basic HTTP Error Response
type ErrResponse struct {
	Code   int         `json:"code"`             // http response status code
	Status string      `json:"status"`           // user-level status message
	Errors interface{} `json:"errors,omitempty"` // application-level error
}

func (e ErrResponse) MarshalToHTTPResponseWriter(w http.ResponseWriter) (int, error) {
	d, err := easyjson.Marshal(e)
	if err != nil {
		return 0, err
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Content-Length", strconv.Itoa(len(d)))
	w.WriteHeader(e.Code)
	return w.Write(d)
}

func BadRequest(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusBadRequest,
		Status: http.StatusText(http.StatusBadRequest),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

func Conflict(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusConflict,
		Status: http.StatusText(http.StatusConflict),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

func Forbidden(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusForbidden,
		Status: http.StatusText(http.StatusForbidden),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

func InternalServerError(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusInternalServerError,
		Status: http.StatusText(http.StatusInternalServerError),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

func NotFound(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusNotFound,
		Status: http.StatusText(http.StatusNotFound),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

func Unauthorized(w http.ResponseWriter, msg interface{}) (int, error) {
	return ErrResponse{
		Code:   http.StatusUnauthorized,
		Status: http.StatusText(http.StatusUnauthorized),
		Errors: msg,
	}.MarshalToHTTPResponseWriter(w)
}

type (
	// Category4094953247View represents the data serialized for the following serialization group combinations:
	// []
	Category4094953247View struct {
		ID   int    `json:"id,omitempty"`
		Name string `json:"name,omitempty"`
	}
	Category4094953247Views []*Category4094953247View
)

func NewCategory4094953247View(e *ent.Category) *Category4094953247View {
	if e == nil {
		return nil
	}
	return &Category4094953247View{
		ID:   e.ID,
		Name: e.Name,
	}
}

func NewCategory4094953247Views(es []*ent.Category) Category4094953247Views {
	if len(es) == 0 {
		return nil
	}
	r := make(Category4094953247Views, len(es))
	for i, e := range es {
		r[i] = NewCategory4094953247View(e)
	}
	return r
}

type (
	// Equipment3958372643View represents the data serialized for the following serialization group combinations:
	// []
	Equipment3958372643View struct {
		ID         int       `json:"id,omitempty"`
		CreateTime time.Time `json:"create_time,omitempty"`
		UpdateTime time.Time `json:"update_time,omitempty"`
		Name       string    `json:"name,omitempty"`
		Condition  string    `json:"condition,omitempty"`
	}
	Equipment3958372643Views []*Equipment3958372643View
)

func NewEquipment3958372643View(e *ent.Equipment) *Equipment3958372643View {
	if e == nil {
		return nil
	}
	return &Equipment3958372643View{
		ID:         e.ID,
		CreateTime: e.CreateTime,
		UpdateTime: e.UpdateTime,
		Name:       e.Name,
		Condition:  e.Condition,
	}
}

func NewEquipment3958372643Views(es []*ent.Equipment) Equipment3958372643Views {
	if len(es) == 0 {
		return nil
	}
	r := make(Equipment3958372643Views, len(es))
	for i, e := range es {
		r[i] = NewEquipment3958372643View(e)
	}
	return r
}

type (
	// Vehicle2530256765View represents the data serialized for the following serialization group combinations:
	// []
	Vehicle2530256765View struct {
		ID         int       `json:"id,omitempty"`
		CreateTime time.Time `json:"create_time,omitempty"`
		UpdateTime time.Time `json:"update_time,omitempty"`
		Make       string    `json:"make,omitempty"`
		Model      string    `json:"model,omitempty"`
		Miles      int64     `json:"miles,omitempty"`
		Mpg        int64     `json:"mpg,omitempty"`
		Owner      string    `json:"owner,omitempty"`
		Year       string    `json:"year,omitempty"`
		Active     bool      `json:"active,omitempty"`
		Condition  string    `json:"condition,omitempty"`
	}
	Vehicle2530256765Views []*Vehicle2530256765View
)

func NewVehicle2530256765View(e *ent.Vehicle) *Vehicle2530256765View {
	if e == nil {
		return nil
	}
	return &Vehicle2530256765View{
		ID:         e.ID,
		CreateTime: e.CreateTime,
		UpdateTime: e.UpdateTime,
		Make:       e.Make,
		Model:      e.Model,
		Miles:      e.Miles,
		Mpg:        e.Mpg,
		Owner:      e.Owner,
		Year:       e.Year,
		Active:     e.Active,
		Condition:  e.Condition,
	}
}

func NewVehicle2530256765Views(es []*ent.Vehicle) Vehicle2530256765Views {
	if len(es) == 0 {
		return nil
	}
	r := make(Vehicle2530256765Views, len(es))
	for i, e := range es {
		r[i] = NewVehicle2530256765View(e)
	}
	return r
}
