// Code generated by entc, DO NOT EDIT.

package vehicle

import (
	"fmt"
	"time"
)

const (
	// Label holds the string label denoting the vehicle type in the database.
	Label = "vehicle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMake holds the string denoting the make field in the database.
	FieldMake = "make"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldMiles holds the string denoting the miles field in the database.
	FieldMiles = "miles"
	// FieldMpg holds the string denoting the mpg field in the database.
	FieldMpg = "mpg"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// Table holds the table name of the vehicle in the database.
	Table = "vehicles"
)

// Columns holds all SQL columns for vehicle fields.
var Columns = []string{
	FieldID,
	FieldMake,
	FieldModel,
	FieldMiles,
	FieldMpg,
	FieldOwner,
	FieldYear,
	FieldActive,
	FieldTags,
	FieldCondition,
	FieldCreateTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// UpdateDefaultCreateTime holds the default value on update for the "create_time" field.
	UpdateDefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// Condition defines the type for the "condition" enum field.
type Condition string

// Condition values.
const (
	ConditionUNSPECIFIED Condition = "UNSPECIFIED"
	ConditionMINT        Condition = "MINT"
	ConditionGOOD        Condition = "GOOD"
	ConditionPOOR        Condition = "POOR"
	ConditionBROKEN      Condition = "BROKEN"
)

func (c Condition) String() string {
	return string(c)
}

// ConditionValidator is a validator for the "condition" field enum values. It is called by the builders before save.
func ConditionValidator(c Condition) error {
	switch c {
	case ConditionUNSPECIFIED, ConditionMINT, ConditionGOOD, ConditionPOOR, ConditionBROKEN:
		return nil
	default:
		return fmt.Errorf("vehicle: invalid enum value for condition field: %q", c)
	}
}
