server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
storage:
  database:
    driver: "${DB_DRIVER:postgres}"
    source: "${DB_URI:postgres://postgres:postgres@localhost/postgres?sslmode=disable}"
    migrate: true
    debug: false
