// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/open-farms/inventory/ent/equipment"
	"github.com/open-farms/inventory/ent/schema"
	"github.com/open-farms/inventory/ent/vehicle"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	equipmentFields := schema.Equipment{}.Fields()
	_ = equipmentFields
	// equipmentDescName is the schema descriptor for name field.
	equipmentDescName := equipmentFields[1].Descriptor()
	// equipment.DefaultName holds the default value on creation for the name field.
	equipment.DefaultName = equipmentDescName.Default.(string)
	// equipmentDescID is the schema descriptor for id field.
	equipmentDescID := equipmentFields[0].Descriptor()
	// equipment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	equipment.IDValidator = equipmentDescID.Validators[0].(func(uint64) error)
	vehicleFields := schema.Vehicle{}.Fields()
	_ = vehicleFields
	// vehicleDescID is the schema descriptor for id field.
	vehicleDescID := vehicleFields[0].Descriptor()
	// vehicle.IDValidator is a validator for the "id" field. It is called by the builders before save.
	vehicle.IDValidator = vehicleDescID.Validators[0].(func(uint64) error)
}
