// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Vehicle is the predicate function for vehicle builders.
type Vehicle func(*sql.Selector)
